language: minimal

before_install:
    - echo "Before install"

install:
    - echo "Install"

before_script:
    - echo "Before the script phase"

script:
    - echo "The main task"
    - exit 0

after_script:
    - echo "After the script phase."
    - echo $TRAVIS_TEST_RESULT

after_success:
    - echo "After success"

after_failure:
    - echo "After failure"

